#
# Makefile for Proxy Lab
#
# The Makefile will build the proxy using all .c and .h files found in the
# current directory. It will not be submitted with your code.
#
# If you have additional .c or .h files (e.g. for building a separate test
# program), you can add those files to .tarignore.
#
# Autolab will execute the command "make proxy" on your specific
# Makefile to build your proxy from sources.
#
SHELL = /bin/bash
CC = gcc
CFLAGS = -g -Og -Wall -std=c99 -MMD -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=700
LDLIBS = -lpthread

# Uncomment this to enable debug macros
# CFLAGS += -DDEBUG

# For proxylab, LLVM is only used for clang-format
LLVM_PATH = /usr/local/depot/llvm-7.0/bin/
ifneq (,$(wildcard /usr/lib/llvm-7/bin/))
  LLVM_PATH = /usr/lib/llvm-7/bin/
endif

# Targets to compile
HANDIN_TAR = proxylab-handin.tar
FILES = proxy $(HANDIN_TAR)

# Find files to be used for handin
HANDIN_FILES = $(shell \
  tar cvf /dev/null \
    --exclude-from=.gitignore \
    --exclude-from=.tarignore \
    $$(find . -type f))

# Filter .c and .h files
SOURCES = $(filter %.c,$(HANDIN_FILES))
DEPS = $(filter %.h,$(HANDIN_FILES))
ifeq ($(SOURCES),)
  $(error No .c files in current directory to make.)
endif

# Default build rule
.PHONY: all
all: $(FILES) tiny-code

.PHONY: tiny-code
tiny-code:
	(cd tiny; make -s)

# Autogenerated rules to build object files
OBJECTS = $(SOURCES:%.c=%.o)
-include $(SOURCES:%.c=%.d)

# Link proxy executable
proxy: $(OBJECTS)

.PHONY: clean
clean:
	rm -f *~ *.o *.d core $(FILES)
	rm -rf logs source_files response_files results.log get_files
	(cd tiny; make clean)

# Include rules for submit, format, etc
FORMAT_FILES = $(SOURCES) $(DEPS)
include helper.mk

# Add check-format dependencies
ifneq ($(NOFORMAT),1)
$(HANDIN_TAR): | check-format
endif
